### PR TITLE
upgraded rqt_pose_view

### PR DESCRIPTION
**Pull request by DorianScholz**
to search through message classes for Pose, Quaternion or Point data

Based on the idea from https://github.com/ros-visualization/rqt_robot_plugins/pull/116

### CODE REVIEW

**Comment by DorianScholz** [comment]
I just realized, the two static methods _find_slot_type_bfs and _find_slot_type_dfs should better go into rqt_py_common in rqt_common_plugins so they can be reused.
Will fix that later. 
For reviewing the functionality this will do.

**Comment by christianrauch** [comment]
Thanks for working on a proper implementation of this functionality.
When I drag a `PoseStamped` or `Imu` on the widget, I get:
```
Traceback (most recent call last):
  File "[workspace]/src/rqt_robot_plugins/rqt_pose_view/src/rqt_pose_view/pose_view_widget.py", line 250, in dragEnterEvent
    quaternion_slot_path, point_slot_path = self._get_slot_paths(msg_class)
  File "[workspace]/src/rqt_robot_plugins/rqt_pose_view/src/rqt_pose_view/pose_view_widget.py", line 329, in _get_slot_paths
    pose_slot_path = self._find_slot_type_bfs(msg_class, Pose)
  File "[workspace]/src/rqt_robot_plugins/rqt_pose_view/src/rqt_pose_view/pose_view_widget.py", line 317, in _find_slot_type_bfs
    slot_type, _, _ = roslib.msgs.parse_type(slot_type)
AttributeError: 'module' object has no attribute 'msgs'
```
It is working with regular `Pose` messages as before.

**Comment by DorianScholz** [comment]
Thank you for testing this. 
Quite interestingly it worked for me on indigo already for posestamped and imu messages.
Which ros distribution are you using? 

Now I explicitly import the roslib.msgs module which hopefully fixes your problem. 
Could you please try again, thanks!

**Comment by christianrauch** [comment]
I am using `kinetic`. The fix solved the problem.
Now I can use the PoseWidget with `PostStamped` and `Imu` topics. Thanks.

**Comment by DorianScholz** [comment]
Great, then I will refactor it so the common code is in rqt_py_common and then merge it.
Thanks for your input and feedback!

**Comment by DorianScholz** [comment]
So, I moved the generic functionality to rqt_py_common now.
Would you be so kind to test this version once more?
If you do, don't forget to also pull the updated rqt_py_common package from https://github.com/ros-visualization/rqt_common_plugins as well.

**Comment by christianrauch** [comment]
This is working at least for `PoseStamped` and `Imu`.
Thanks for implementing.

**Pull request merged**
