### PR TITLE
Added UTF-8 support for diagnostic messages to rqt_robot_monitor

### LINKED ISSUE #79: rqt_robot_monitor: UTF8 Messages not displayed correctly
The robot monitor plugin does not appear to support using UTF8 strings. As shown below trying to send a UTF8 degree symbol (C2 B0) results in the first byte of the UTF8 sequence being treated as a seperate character.

rqt_robot_monitor-utf8

### PR DESCRIPTION
**Pull request by mitchellwills**
Fixes #79

### CODE REVIEW

**Comment by mitchellwills** [comment]
@dirk-thomas Any thoughts on this?

**Comment by dirk-thomas** [comment]
The code is incompatible with Python 3 which makes me hesitant to merge it as-is.

**Comment by mitchellwills** [comment]
Are there any resource on setting up a python 3 ROS installation? I spent a while searching for instructions and have been unable to find any.

**Comment by dirk-thomas** [comment]
No, sadly there are none. The easiest way is to create a Python 3 virtual env, install all ROS Python packages in there and then compile ROS from source using the CMake variable `PYTHON_VERSION=3`.

**Comment by mitchellwills** [comment]
So while i'm still having some issues getting everything running with python3 (tf2 still hasn't been upgraded ros/geometry_experimental#50 so I need to be more fine grain about what I compile) it looks like no modifications should be needed when running under python3. From looking at the generated python message serialization/deserialization code it looks like when running under python3 strings in messages are automatically decoded using UTF8 when they are received (for a simple example see the generated code for std_msgs/String). Would a pull request that uses a similar technique to the message generation to only activate when running under python 2 then be accepted?

**Comment by mitchellwills** [comment]
I actually did get rqt_robot_monitor running under python3, but get the following stack trace when running it:
```
Traceback (most recent call last):
  File "/home/mitchell/python3venv/ros_catkin_ws/install/lib/rqt_robot_monitor/rqt_robot_monitor", line 8, in <module>
    sys.exit(main.main(sys.argv, standalone='rqt_robot_monitor.robot_monitor_plugin.RobotMonitorPlugin'))
  File "/home/mitchell/python3venv/ros_catkin_ws/install/lib/python3/dist-packages/rqt_gui/main.py", line 59, in main
    return super(Main, self).main(argv, standalone=standalone, plugin_argument_provider=plugin_argument_provider, plugin_manager_settings_prefix=str(hash(os.environ['ROS_PACKAGE_PATH'])))
  File "/home/mitchell/python3venv/ros_catkin_ws/install/lib/python3/dist-packages/qt_gui/main.py", line 336, in main
    from python_qt_binding import QT_BINDING
  File "/home/mitchell/python3venv/ros_catkin_ws/install/lib/python3/dist-packages/python_qt_binding-0.2.14-py3.4.egg/python_qt_binding/__init__.py", line 55, in <module>
  File "/home/mitchell/python3venv/ros_catkin_ws/install/lib/python3/dist-packages/python_qt_binding-0.2.14-py3.4.egg/python_qt_binding/binding_helper.py", line 33, in <module>
ImportError: No module named '__builtin__'
```

**Comment by dirk-thomas** [comment]
That is weird. The code should include `builtins` for Python 3 and `__builtin__ as builtins` for Python 2: https://github.com/ros-visualization/python_qt_binding/blob/9912a6dbde43f75b8fc877e082469e9d6bf625e6/src/python_qt_binding/binding_helper.py#L33-L36

**Comment by mitchellwills** [comment]
Don't know if there is something funky with my virtual env cause the directory ```python_qt_binding-0.2.14-py3.4.egg``` does not even exist in ```/home/mitchell/python3venv/ros_catkin_ws/install/lib/python3/dist-packages/```

**Comment by mitchellwills** [comment]
I'm going to close this because I don't really have a need for it any more and I think this may be better suited for the rospy core anyway (so it applies to all strings)

**Pull request closed without merging**
